https-portal:
    image: steveltn/https-portal:1
    ports:
      - '80:80'
      - '443:443'
    links:
      - durchhaltevermoegen
    restart: always
    environment:
      DOMAINS: 'tuebinger-durchhaltevermoegen.live -> http://durchhaltevermoegen:80'
  
durchhaltevermoegen:
    image: LeanderK/Durchhaltevermoegeny